/**
 * Auto-generated MCP metadata
 * Generated at: 2026-04-10T15:49:42.312Z
 * DO NOT EDIT - This file is automatically generated by scripts/extract-tools.ts
 */

export interface ToolMetadata {
  name: string;
  description: string;
  category: string;
  parameters?: Record<string, any>;
}

export interface PromptMetadata {
  name: string;
  description: string;
  category: string;
}

export interface MCPMetadata {
  tools: ToolMetadata[];
  prompts: PromptMetadata[];
  resources: any[];
}

export const metadata: MCPMetadata = {
  "tools": [
    {
      "name": "checkMonitors",
      "description": "Check all monitors and their statuses.",
      "category": "Core"
    },
    {
      "name": "createDashboard",
      "description": "Create a new dashboard from a JSON document. The dashboard JSON must include required fields: name, owner, charts, layout, refreshTime, schemaVersion (2), timeWindowStart, timeWindowEnd. Set owner to",
      "category": "Core"
    },
    {
      "name": "deleteDashboard",
      "description": "Delete a dashboard by its UID. This action is irreversible.",
      "category": "Core"
    },
    {
      "name": "exportDashboard",
      "description": "Export a dashboard as JSON by its UID. Returns the full dashboard document that can be used to create or update dashboards via the API.",
      "category": "Core"
    },
    {
      "name": "getDashboard",
      "description": "Get detailed information about a specific dashboard by UID.",
      "category": "Core"
    },
    {
      "name": "getDatasetFields",
      "description": "List all fields in a dataset.",
      "category": "Core"
    },
    {
      "name": "getMetricTagValues",
      "description": "List all values for a specific tag in a metrics dataset. Useful for discovering filter values before querying.",
      "category": "Core"
    },
    {
      "name": "getMonitorHistory",
      "description": "Get recent check history of monitor. Use the checkMonitors() tool to list all the monitors.",
      "category": "Core"
    },
    {
      "name": "getSavedQueries",
      "description": "Retrieve saved/starred queries from Axiom - shows APL queries that users have bookmarked for reuse",
      "category": "Core"
    },
    {
      "name": "listDashboards",
      "description": "List all available dashboards. Shows user-created dashboards with their metadata.",
      "category": "Core"
    },
    {
      "name": "listDatasets",
      "description": "List all available datasets. For datasets you are curious about, use getDatasetFields() tool to find their schema.",
      "category": "Core"
    },
    {
      "name": "listMetrics",
      "description": "List all available metrics in a metrics dataset (kind",
      "category": "Core"
    },
    {
      "name": "listMetricTags",
      "description": "List all available tags (dimensions) in a metrics dataset. Tags can be used to filter and group metrics queries.",
      "category": "Core"
    },
    {
      "name": "queryDataset",
      "description": "# Instructions 1. Query Axiom datasets using Axiom Processing Language (APL). The query must be a valid APL query string. 2. ALWAYS get the schema of the dataset before running queries rather than guessing. You can do this by getting a single event and projecting all fields. 3. Keep in mind that there",
      "category": "Core"
    },
    {
      "name": "queryMetrics",
      "description": "# Instructions 1. Query OpenTelemetry metrics stored in Axiom using MPL (Metrics Processing Language). NOT APL. 2. The query targets a metrics dataset (kind",
      "category": "Core"
    },
    {
      "name": "searchMetrics",
      "description": "Search for metrics matching a known tag value (e.g. a service name, host, or endpoint). Returns metric names associated with the given value. Useful when you know a tag value but not which metrics contain it.",
      "category": "Core"
    },
    {
      "name": "updateDashboard",
      "description": "Update an existing dashboard by UID. Provide the full dashboard JSON document. Use overwrite=true to skip version conflict checks (last-write-wins), or provide the current version number for optimistic concurrency control.",
      "category": "Core"
    }
  ],
  "prompts": [
    {
      "name": "correlate-events-across-datasets",
      "description": "Find patterns and correlations between events across multiple datasets",
      "category": "Core"
    },
    {
      "name": "data-quality-investigation",
      "description": "Investigate data quality issues including missing data, inconsistencies, and collection problems",
      "category": "Core"
    },
    {
      "name": "detect-anomalies-in-events",
      "description": "Generic anomaly detection using statistical analysis and pattern recognition across any event dataset",
      "category": "Core"
    },
    {
      "name": "establish-performance-baseline",
      "description": "Establish performance baselines for a dataset to enable effective monitoring and anomaly detection",
      "category": "Core"
    },
    {
      "name": "explore-unknown-dataset",
      "description": "Systematic exploration of an unknown dataset to understand its structure, content, and potential use cases",
      "category": "Core"
    },
    {
      "name": "monitor-health-analysis",
      "description": "Comprehensive analysis of monitor health, alert patterns, and effectiveness",
      "category": "Core"
    }
  ],
  "resources": []
};

export const toolsByCategory = metadata.tools.reduce((acc, tool) => {
  if (!acc[tool.category]) {
    acc[tool.category] = [];
  }
  acc[tool.category].push(tool);
  return acc;
}, {} as Record<string, ToolMetadata[]>);

export const promptsByCategory = metadata.prompts.reduce((acc, prompt) => {
  if (!acc[prompt.category]) {
    acc[prompt.category] = [];
  }
  acc[prompt.category].push(prompt);
  return acc;
}, {} as Record<string, PromptMetadata[]>);
